import AppFooter from "@/component/app.footer";
import AppHeader from "@/component/app.header";
import type { Metadata } from "next";
import 'semantic-ui-css/semantic.min.css'
import "./globals.css";
import SongPlayBottom from "@/component/songPlayBottom/songPlayBottom.component";
import { SongPlayContextProvider } from "@/contexts/SongPlayContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SongPlayContextProvider>
          <div className="container">
            <AppHeader />
            <div className="container_main">
              {children}
            </div>
            <AppFooter />
            <SongPlayBottom />
          </div>
        </SongPlayContextProvider>
      </body>
    </html>
  );
}
